dbConfig:
    dbConfigFile: ./primary.db
    dbConfigPoolSize: 20

pabWebserverConfig:
  baseUrl: http://localhost:9080
  staticDir: .

walletServerConfig:
  baseUrl: http://localhost:9081
  wallet: 
    getWallet: 1

nodeServerConfig:
  mscBaseUrl: http://localhost:9082
  mscSocketPath: ./node-server.sock
  mscSlotLength: 5
  mscBlockReaper:
    brcInterval: 6000000
    brcBlocksToKeep: 100000
  mscInitialTxWallets:
    - getWallet: 1
    - getWallet: 2
    - getWallet: 3
    - getWallet: 4
    - getWallet: 5
    - getWallet: 6
    - getWallet: 7
    - getWallet: 8
    - getWallet: 9
    - getWallet: 10

chainIndexConfig:
  ciBaseUrl: http://localhost:9083
  ciWatchedAddresses:
    [ { "tag": "PubKeyAddress"
      , "contents": { "getPubKeyHash" : "9d61b19deffd5a60ba844af492ec2cc44449c5697b326919703bac031cae7f60" } }
    , { "tag": "PubKeyAddress"
      , "contents": { "getPubKeyHash" : "4ccd089b28ff96da9db6c346ec114e0f5b8a319f35aba624da8cf6ed4fb8a6fb" } }
    , { "tag": "PubKeyAddress"
      , "contents": { "getPubKeyHash" : "c5aa8df43f9f837bedb7442f31dcb7b166d38535076f094b85ce3a2e0b4458f7" } }
    , { "tag": "PubKeyAddress"
      , "contents": { "getPubKeyHash" : "691865bfc82a1e4b574eecde4c7519093faf0cf867380234e3664645c61c5f79" } }
    , { "tag": "PubKeyAddress"
      , "contents": { "getPubKeyHash" : "3b26516fb3dc88eb181b9ed73f0bcd52bcd6b4c788e4bcaf46057fd078bee073" } }
    , { "tag": "PubKeyAddress"
      , "contents": { "getPubKeyHash" : "edc6f5fbdd1cee4d101c063530a30490b221be68c036f5b07d0f953b745df192" } }
    , { "tag": "PubKeyAddress"
      , "contents": { "getPubKeyHash" : "a980f892db13c99a3e8971e965b2ff3d41eafd54093bc9f34d1fd22d84115bb6" } }
    , { "tag": "PubKeyAddress"
      , "contents": { "getPubKeyHash" : "9acad959d216212d789a119252ebfe0c96512a23c73bd9f3b202292d6916a738" } }
    , { "tag": "PubKeyAddress"
      , "contents": { "getPubKeyHash" : "d5aeee41eeb0e9d1bf8337f939587ebe296161e6bf5209f591ec939e1440c300" } }
    , { "tag": "PubKeyAddress"
    , "contents": { "getPubKeyHash" : "0a47d10452ae2febec518a1c7c362890c3fc1a49d34b03b6467d35c904a8362d" } }
    ]

requestProcessingConfig:
  requestProcessingInterval: 1

signingProcessConfig:
  spBaseUrl: http://localhost:9084
  spWallet: 
    getWallet: 1

metadataServerConfig:
  mdBaseUrl: http://localhost:9085

