name: "Build and Deploy to Github Pages"
on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  build-haddock-site:
    runs-on: ubuntu-latest

    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - uses: actions/checkout@v3

      - uses: nixbuild/nix-quick-install-action@v25
        with:
          # 2.14.1 seems to have issues, see https://github.com/nixbuild/nix-quick-install-action/issues/29
          nix_version: '2.13.3'
          nix_conf: |
            experimental-features = nix-command flakes
            accept-flake-config = true

      - name: Build haddock site
        run: |
          nix build .#combined-plutus-haddock
          mkdir dist
          cp -RL ./result/share/doc/* ./dist/

      - name: Upload pages artifacts 
        uses: actions/upload-pages-artifact@v1
        with:
          path: ./dist
          target-folder: ${{ github.ref_name }}

      - name: Deploy pages
        id: deployment
        uses: actions/deploy-pages@v2