name: "Build and Deploy to Github Pages"
on:
  workflow_dispatch:
  push:
    branches:
      - master
jobs:
  build-haddock-site:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    environment:
      name: github-pages
    steps:
      - uses: actions/checkout@v4
      - uses: nixbuild/nix-quick-install-action@v28
        with:
          nix_conf: |
            experimental-features = nix-command flakes
            accept-flake-config = true
      - name: Build Haddock Site
        run: |
          nix build .#combined-haddock
          mkdir dist
          cp -RL ./result/share/doc/* ./dist/
      - uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          target-folder: ${{ github.ref_name }}
          # We publish our haddock, which is non-trivially big. 
          # So keeping the whole history is expensive, and anyway we don't need it.
          single-commit: true
