# This workflow builds and publishes the metatheory site to:
# https://intersectmbo.github.io/plutus/metatheory/$version
# And optionally to:
# https://intersectmbo.github.io/plutus/metatheory/latest

name: "ðŸ”® Metatheory Site"

on:
  workflow_dispatch:
    inputs:
      ref:
        description: |
          The $ref to build off of, e.g. "1.29.0.0", "master", or any other valid git ref.
          When making a release, this is usually the version tag, e.g. "1.29.0.0", and will be
          equal to the $destination input below. When back-porting this could be a commit sha instead.
        required: true
        type: string

      destination:
        description: |
          The $destination folder, e.g. when "1.29.0.0" the metatheory will be deploy to:
          https://intersectmbo.github.io/plutus/metatheory/1.29.0.0
        required: true
        type: string
  
      latest: 
        description: |
          If true, then the metatheory site will also be deploy to:
          https://intersectmbo.github.io/plutus/metatheory/latest.
          You want to leave this to true unless you are deploying old versions or back-porting.
        type: boolean
        required: true 
        default: true

jobs:
  deploy:
    name: Deploy
    runs-on: [self-hosted, plutus-shared]
    permissions:
      contents: write
    environment:
      name: github-pages
    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          ref: ${{ inputs.ref }}

      - name: Build Site
        run: | 
          nix build --accept-flake-config .#plutus-metatheory-site
          mkdir _site
          cp -RL result/* _site

      - name: Deploy Site
        uses: JamesIves/github-pages-deploy-action@v4.6.1
        with:
          folder: _site
          target-folder: metatheory/${{ inputs.destination }}
          single-commit: true
        
      - name: Deploy Latest
        if: ${{ inputs.latest == true }}
        uses: JamesIves/github-pages-deploy-action@v4.6.1
        with:
          folder: _site
          target-folder: metatheory/latest
          single-commit: true

