# This workflow publishes the Agda metatheory site to:
#   https://intersectmbo.github.io/plutus/metatheory/$version
# Where $version should be a release version tag.
# Optionally the $version branch can also be deployed to:
#   https://intersectmbo.github.io/plutus/metatheory/latest  

name: "ðŸ”® Metatheory Site"

on:
  workflow_dispatch:
    inputs:
      version:
        description: |
          The release version tag. For example if $version == "1.29.0.0" then the 
          current contents of the branch tagged "1.29.0.0" will be deployed to: 
            https://intersectmbo.github.io/plutus/metatheory/$version
        required: true
        type: string

      latest: 
        description: |
          If true, then the $version branch will also be deployed to:
            https://intersectmbo.github.io/plutus/metatheory/latest
          You want to leave this to true unless you are deploying old versions.
        type: boolean
        required: true 
        default: true

jobs:
  publish:
    name: Publish
    runs-on: [self-hosted, plutus-shared]
    permissions:
      contents: write
    environment:
      name: github-pages
    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          ref: ${{ inputs.version }}

      - name: Build Site
        run: | 
          nix build --accept-flake-config .#plutus-metatheory-site
          cp -RL ./result/* ./_site

      - name: Deploy Site
        uses: JamesIves/github-pages-deploy-action@v4.6.1
        with:
          folder: _site
          target-folder: metatheory/${{ inputs.version }}
          single-commit: true
        
      - name: Deploy Latest
        if: ${{ inputs.latest == true }}
        uses: JamesIves/github-pages-deploy-action@v4.6.1
        with:
          folder: _site
          target-folder: metatheory/latest
          single-commit: true

