name: Nightly Test Suite

on:
  schedule:
    - cron: 0 0 * * * # daily at midnight

  workflow_dispatch: # or manually dispatch the job
    inputs:
      hedgehog-tests:
        description: Numer of tests to run (--hedgehog-tests XXXXX)
        required: false
        default: "100000"

env: 
  HEDGEHOG_TESTS: ${{ github.event.inputs.hedgehog-tests || 100000 }}

jobs:
  nightly-test-suite:
    timeout-minutes: 14400
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Use Magic Nix Cache
        uses: DeterminateSystems/magic-nix-cache-action@main
      
      - name: plutus-core-nightly
        if: always()
        run: |
          pushd plutus-core
          nix run --no-warn-dirty --accept-flake-config .#plutus-core-test -- --hedgehog-tests $HEDGEHOG_TESTS
          popd

      - name: plutus-ir-nightly
        if: always()
        run: |
          pushd plutus-core
          nix run --no-warn-dirty --accept-flake-config .#plutus-ir-test -- --hedgehog-tests $HEDGEHOG_TESTS
          popd
