# This workflow moves issues and pull requests to the next sprint iteration of 
# the Plutus Backlog project. In practice, all open backlog items in the Current
# Iteration (the one that is still in progress) will be moved to the Next 
# Iteration (the one that will start next).
# This workflow must be run manually from the GitHub Actions page.
# In practice you want to run this on the last day of the current sprint, the 
# day before the next sprint begins.

name: "üõº Sprint Issues Rollover"

on:
  workflow_dispatch:

jobs:
  Run:
    runs-on: ubuntu-latest

    steps:
    - uses: blombard/move-to-next-iteration@master
      with:
        owner: IntersectMBO
        number: 18 # Find this number by looking at the project's page URL
        token: ${{ secrets.PLUTUS_BACKLOG_AUTOMATION }} # Needs project write permissions
        iteration-field: Sprint
        iteration: current
        new-iteration: next
        excluded-statuses: ‚ùå - won't do,üöÄ - done