# This workflows automatically moves issues and pull requests to the next 
# iteration of our Plutus Backlog project when a new sprint begins.

name: "ðŸ›¼ Sprint Issues Rollover"

on:
  workflow_dispatch:
  schedule:
    - cron: '0 5 * * 1' # 5am on Monday

jobs:
  Run:
    runs-on: ubuntu-latest

    steps:
    - uses: blombard/move-to-next-iteration@master
      with:
        owner: IntersectMBO
        number: 18
        token: ${{ secrets.PROJECT_PAT }}
        iteration-field: Sprint
        iteration: last
        new-iteration: current
        excluded-statuses: won't do,done