# This workflows moves issues and pull requests to the next iteration of our 
# Plutus Backlog project when a new sprint begins.
# To do so, this workflow must be run manually from the GitHub Actions page.

name: "ğŸ›¼ Sprint Issues Rollover"

on:
  workflow_dispatch:

jobs:
  Run:
    runs-on: ubuntu-latest

    steps:
    - uses: blombard/move-to-next-iteration@master
      with:
        owner: IntersectMBO
        number: 35
        token: ${{ secrets.PLUTUS_BACKLOG_AUTOMATION }}
        iteration-field: Sprint
        iteration: last
        new-iteration: current
        excluded-statuses: âŒ - Won't Do,ğŸš€ - Done
